[package]
name = "lift"
version = "0.1.0"
authors = ["Jordan <jordan.bankole@epitech.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
